apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordersvc-deployment
  namespace: apptordev
  labels:
    app: ordersvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordersvc
  template:
    metadata:
      labels:
        app: ordersvc
    spec:
      containers:
      - name: ordersvc
        image: micronauttest/ordersvc
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
      serviceAccountName: apptor-sa

---
apiVersion: v1
kind: Service
metadata:
  name: ordersvc
  namespace: apptordev
spec:
  type: NodePort
  selector:
    app: ordersvc
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
#      nodePort: 30008