micronaut:
  application:
    name: customer-service
  server:
    port: 8080
  http:
    client:
      read-timeout: 100s
#    services:
#      ordersvc:
#        url: http://localhost:8081

#jackson:
#  module-scan: false
