apiVersion: apps/v1
kind: Deployment
metadata:
  name: customersvc-deployment
  namespace: test
  labels:
    app: customersvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customersvc
  template:
    metadata:
      labels:
        app: customersvc
    spec:
      containers:
      - name: customersvc
        image: micronauttest/customersvc
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
      serviceAccountName: test-sa
---
apiVersion: v1
kind: Service
metadata:
  name: customersvc
  namespace: test
spec:
  type: NodePort
  selector:
    app: customersvc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007