apiVersion: skaffold/v2beta23
kind: Config
build:
  artifacts:
  - image: micronauttest/customersvc
    context: .
    jib: {}
  tagPolicy:
    gitCommit: {}
portForward:
  - resourceType: service
    resourceName: customersvc
    port: 8080
    localPort: 8080
